// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Tape = require("tape");

var FFI = /* module */[];

function make(prim, prim$1) {
  Tape(prim, prim$1);
  return /* () */0;
}

function t(param) {
  Tape("sample", param);
  return /* () */0;
}

exports.FFI = FFI;
exports.make = make;
exports.t = t;
/* tape Not a pure module */
