// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function invariant(q) {
  if (q[0]) {
    return q;
  } else {
    return /* tuple */[
            List.rev(q[1]),
            /* [] */0
          ];
  }
}

var empty = /* tuple */[
  /* [] */0,
  /* [] */0
];

function isEmpty(x) {
  if (x[0] || x[1]) {
    return true;
  } else {
    return false;
  }
}

function push(param, e) {
  return invariant(/* tuple */[
              param[0],
              /* :: */[
                e,
                param[1]
              ]
            ]);
}

function head(q) {
  var match = q[0];
  if (match) {
    return Js_primitive.some(match[0]);
  }
  
}

function tail(q) {
  var match = q[0];
  if (match) {
    var q$prime_000 = match[1];
    var q$prime_001 = q[1];
    var q$prime = /* tuple */[
      q$prime_000,
      q$prime_001
    ];
    return invariant(q$prime);
  }
  
}

var M = /* module */[
  /* empty */empty,
  /* isEmpty */isEmpty,
  /* push */push,
  /* head */head,
  /* tail */tail
];

exports.M = M;
exports.empty = empty;
exports.isEmpty = isEmpty;
exports.push = push;
exports.head = head;
exports.tail = tail;
/* No side effect */
