// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


var Lazy = /* module */[
  /* List */0,
  /* RealTimeQueue */0
];

var BatchedQueue = 0;

var BankersQueue = 0;

exports.Lazy = Lazy;
exports.BatchedQueue = BatchedQueue;
exports.BankersQueue = BankersQueue;
/* No side effect */
